version: '3'
services:
  redis_cron:
    image: redis:latest
    container_name: redis_cron
    ports:
      - "30637:6379"
  mariadb_cron:
    image: mariadb:latest
    container_name: mariadb_cron
    environment:
      MARIADB_USER: user1
      MARIADB_PASSWORD: user1
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_cron
    volumes:
      - ../mariadb_cron_data:/var/lib/mysql
    ports:
      - "30055:3306"
