/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "auth": {
        "time": {
            "hour": string;
            "day": string;
        };
        "errors": {
            "wrong_login_or_password": string;
            "ban_login": string;
        };
    };
    "job": {
        "errors": {
            "not_found": string;
            "bad_req": string;
        };
    };
    "main": {
        "messages": {
            "server_port": string;
            "incoming_req": string;
        };
        "doc": {
            "title": string;
            "description": string;
        };
    };
    "ssh": {
        "errors": {
            "duplicate": string;
            "no_id": string;
            "not_found": string;
            "cannot_delete": string;
        };
        "messages": {
            "start_all_servers": string;
            "need_add_count": string;
            "add_server_id": string;
            "delete_server_id": string;
            "cron_job_start": string;
            "cron_job_end": string;
        };
    };
    "user": {
        "errors": {
            "duplicate_phone": string;
            "bad_req": string;
            "not_found": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
